import Node, {State, NodeList} from './node';
export {State, NodeList};

export default class Panel extends Node {
	static toolbar(left: any, right?: any) { return m('div.toolbar', left, m('span.spacer'), right); }
	static icon(name: string): MithrilVirtualElement { return m('svg.icon', m('use', {href: 'icon/' + icon_data[name]})); }
	static checkbox(attrs: {id: String, [key: string]: any}, label: string): MithrilVirtualElement { return m('span', m('input[type=checkbox]', attrs), m('label', {for: attrs.id}, label)); }

	protected $minimize: boolean = null;
	protected $close: boolean;

	constructor(state: State) {
		super(state);
		this.$close = state['close'] || false;
	}

	dead() { return this.$close && (!this.children || this.children.length == 0); }
	state() { return super.state().include({close: this.$close}); }

	minimize(val?: boolean) { this.$minimize = val === undefined ? !this.$minimize : val; return this; }
	close() { this.$close = true; return this; }

	view(attr: any, ...elements: any[]) {
		if (this.dead() || this.$close) { return null; }
		attr = attr || {};
		attr.key = this.key;
		attr.class = [
			this.type.replace('/', '-'),
			(this.$minimize === null ? '' : (this.$minimize ? 'min' : 'max')),
			(attr.class || '')
		].join(' ');

		var tree = 'reverse';
		if ('tree' in attr) {
			if (!attr.tree) { tree = 'hide'; }
			else if (typeof attr.tree === 'string') { tree = attr.tree.toLowerCase(); }
		}
		var children = tree === 'hide' ? null : this.children.map(child => child.view());
		if (tree === 'reverse') { children.reverse(); }

		return [
			m('div.panel', attr,
				m('div.control.left',
					this.$minimize === null ? null : (!this.$minimize
						? m('button.min', {onclick: this.minimize.bind(this, true)}, Panel.icon('e/triangle-down'))
						: m('button.max', {onclick: this.minimize.bind(this, false)}, Panel.icon('e/triangle-right')))
				),
				m('div.control.right', m('button.close', {onclick: this.close.bind(this)}, Panel.icon('e/cross'))),
				m('div.content', elements)
			),
			children
		];
	}
}

var icon_data: {[id: string]: string} = {
	'e/add-to-list': 'entypo/add-to-list.svg#Add_to_list',
	'e/add-user': 'entypo/add-user.svg#Add_user',
	'e/address': 'entypo/address.svg#Address',
	'e/adjust': 'entypo/adjust.svg#Adjust',
	'e/air': 'entypo/air.svg#Air',
	'e/aircraft-landing': 'entypo/aircraft-landing.svg#Aircraft_landing',
	'e/aircraft-take-off': 'entypo/aircraft-take-off.svg#Aircraft_take_off',
	'e/aircraft': 'entypo/aircraft.svg#Aircraft',
	'e/align-bottom': 'entypo/align-bottom.svg#Align_bottom',
	'e/align-horizontal-middle': 'entypo/align-horizontal-middle.svg#Horizontal_align_middle',
	'e/align-left': 'entypo/align-left.svg#Align_left',
	'e/align-right': 'entypo/align-right.svg#Align_right',
	'e/align-top': 'entypo/align-top.svg#Align_top',
	'e/align-vertical-middle': 'entypo/align-vertical-middle.svg#Vertical_align_middle',
	'e/archive': 'entypo/archive.svg#Archive',
	'e/area-graph': 'entypo/area-graph.svg#Area_graph',
	'e/arrow-bold-down': 'entypo/arrow-bold-down.svg#Arrow_bold_down',
	'e/arrow-bold-left': 'entypo/arrow-bold-left.svg#Arrow_bold_left',
	'e/arrow-bold-right': 'entypo/arrow-bold-right.svg#Arrow_bold_right',
	'e/arrow-bold-up': 'entypo/arrow-bold-up.svg#Arrow_bold_up',
	'e/arrow-down': 'entypo/arrow-down.svg#Arrow_down',
	'e/arrow-left': 'entypo/arrow-left.svg#Arrow_left',
	'e/arrow-long-down': 'entypo/arrow-long-down.svg#Arrow_long_down',
	'e/arrow-long-left': 'entypo/arrow-long-left.svg#Arrow_long_left',
	'e/arrow-long-right': 'entypo/arrow-long-right.svg#Arrow_long_right',
	'e/arrow-long-up': 'entypo/arrow-long-up.svg#Arrow_long_up',
	'e/arrow-right': 'entypo/arrow-right.svg#Arrow_right',
	'e/arrow-up': 'entypo/arrow-up.svg#Arrow_up',
	'e/arrow-with-circle-down': 'entypo/arrow-with-circle-down.svg#Arrow_circled_down',
	'e/arrow-with-circle-left': 'entypo/arrow-with-circle-left.svg#Arrow_circled_left',
	'e/arrow-with-circle-right': 'entypo/arrow-with-circle-right.svg#Arrow_circled_right',
	'e/arrow-with-circle-up': 'entypo/arrow-with-circle-up.svg#Arrow_circled_up',
	'e/attachment': 'entypo/attachment.svg#Attachment',
	'e/awareness-ribbon': 'entypo/awareness-ribbon.svg#Awareness_ribbon',
	'e/back-in-time': 'entypo/back-in-time.svg#Back_in_time',
	'e/back': 'entypo/back.svg#Back',
	'e/bar-graph': 'entypo/bar-graph.svg#Bar_graph',
	'e/battery': 'entypo/battery.svg#Battery',
	'e/beamed-note': 'entypo/beamed-note.svg#Beamed_note',
	'e/bell': 'entypo/bell.svg#Bell',
	'e/blackboard': 'entypo/blackboard.svg#Blackboard',
	'e/block': 'entypo/block.svg#Block',
	'e/book': 'entypo/book.svg#Book',
	'e/bookmark': 'entypo/bookmark.svg#Bookmark',
	'e/bookmarks': 'entypo/bookmarks.svg#Bookmarks',
	'e/bowl': 'entypo/bowl.svg#Bowl',
	'e/box': 'entypo/box.svg#Box',
	'e/briefcase': 'entypo/briefcase.svg#Briefcase',
	'e/browser': 'entypo/browser.svg#Browser',
	'e/brush': 'entypo/brush.svg#Brush',
	'e/bucket': 'entypo/bucket.svg#Bucket',
	'e/bug': 'entypo/bug.svg#Bug',
	'e/cake': 'entypo/cake.svg#Cake',
	'e/calculator': 'entypo/calculator.svg#Calculator',
	'e/calendar': 'entypo/calendar.svg#Calendar',
	'e/camera': 'entypo/camera.svg#Camera',
	'e/ccw': 'entypo/ccw.svg#CCW',
	'e/chat': 'entypo/chat.svg#Chat',
	'e/check': 'entypo/check.svg#Check',
	'e/chevron-down': 'entypo/chevron-down.svg#Chevron_down',
	'e/chevron-left': 'entypo/chevron-left.svg#Chevron_left',
	'e/chevron-right': 'entypo/chevron-right.svg#Chevron_right',
	'e/chevron-small-down': 'entypo/chevron-small-down.svg#Chevron_small_down',
	'e/chevron-small-left': 'entypo/chevron-small-left.svg#Chevron_small_left',
	'e/chevron-small-right': 'entypo/chevron-small-right.svg#Chevron_small_right',
	'e/chevron-small-up': 'entypo/chevron-small-up.svg#Chevron_small_up',
	'e/chevron-thin-down': 'entypo/chevron-thin-down.svg#Chevron_thin_down',
	'e/chevron-thin-left': 'entypo/chevron-thin-left.svg#Chevron_thin_left',
	'e/chevron-thin-right': 'entypo/chevron-thin-right.svg#Chevron_thin_right',
	'e/chevron-thin-up': 'entypo/chevron-thin-up.svg#Chevron_thin_up',
	'e/chevron-up': 'entypo/chevron-up.svg#Chevron_up',
	'e/chevron-with-circle-down': 'entypo/chevron-with-circle-down.svg#Chevron_circled_down',
	'e/chevron-with-circle-left': 'entypo/chevron-with-circle-left.svg#Chevron_circled_left',
	'e/chevron-with-circle-right': 'entypo/chevron-with-circle-right.svg#Chevron_circled_right',
	'e/chevron-with-circle-up': 'entypo/chevron-with-circle-up.svg#Chevron_circled_up',
	'e/circle-with-cross': 'entypo/circle-with-cross.svg#Circled_cross',
	'e/circle-with-minus': 'entypo/circle-with-minus.svg#Circled_minus',
	'e/circle-with-plus': 'entypo/circle-with-plus.svg#Circled_plus',
	'e/circle': 'entypo/circle.svg#Circle',
	'e/circular-graph': 'entypo/circular-graph.svg#Circular_graph',
	'e/clapperboard': 'entypo/clapperboard.svg#Clapperboard',
	'e/classic-computer': 'entypo/classic-computer.svg#Classic_computer',
	'e/clipboard': 'entypo/clipboard.svg#Clipboard',
	'e/clock': 'entypo/clock.svg#Clock',
	'e/cloud': 'entypo/cloud.svg#Cloud',
	'e/code': 'entypo/code.svg#Code',
	'e/cog': 'entypo/cog.svg#Cog',
	'e/colours': 'entypo/colours.svg#Colours',
	'e/compass': 'entypo/compass.svg#Compass',
	'e/controller-fast-backward': 'entypo/controller-fast-backward.svg#Fast_backward',
	'e/controller-fast-forward': 'entypo/controller-fast-forward.svg#Fast_forward',
	'e/controller-jump-to-start': 'entypo/controller-jump-to-start.svg#Jump_tp_start',
	'e/controller-next': 'entypo/controller-next.svg#Next',
	'e/controller-paus': 'entypo/controller-paus.svg#Paus',
	'e/controller-play': 'entypo/controller-play.svg#Play',
	'e/controller-record': 'entypo/controller-record.svg#Record',
	'e/controller-stop': 'entypo/controller-stop.svg#Stop',
	'e/controller-volume': 'entypo/controller-volume.svg#Volume',
	'e/copy': 'entypo/copy.svg#Copy',
	'e/creative-commons-attribution': 'entypo/creative-commons-attribution.svg#Creative_Commons_Attribution',
	'e/creative-commons-noderivs': 'entypo/creative-commons-noderivs.svg#Creative_Commons_NoDerivs',
	'e/creative-commons-noncommercial-eu': 'entypo/creative-commons-noncommercial-eu.svg#Creative_Commons_NonCommercial_EU',
	'e/creative-commons-noncommercial-us': 'entypo/creative-commons-noncommercial-us.svg#Creative_Commons_NonCommercial_US',
	'e/creative-commons-public-domain': 'entypo/creative-commons-public-domain.svg#Creative_Commons_Public_Domain',
	'e/creative-commons-remix': 'entypo/creative-commons-remix.svg#Creative_Commons_Remix',
	'e/creative-commons-share': 'entypo/creative-commons-share.svg#Creative_Commons_Share',
	'e/creative-commons-sharealike': 'entypo/creative-commons-sharealike.svg#Creative_Commons_ShareAlike',
	'e/creative-commons': 'entypo/creative-commons.svg#Creative_Commons',
	'e/credit-card': 'entypo/credit-card.svg#Credit_card',
	'e/credit': 'entypo/credit.svg#Credit',
	'e/crop': 'entypo/crop.svg#Crop',
	'e/cross': 'entypo/cross.svg#Cross',
	'e/cup': 'entypo/cup.svg#Cup',
	'e/cw': 'entypo/cw.svg#CW',
	'e/cycle': 'entypo/cycle.svg#Cycle',
	'e/database': 'entypo/database.svg#Database',
	'e/dial-pad': 'entypo/dial-pad.svg#Dial_pad',
	'e/direction': 'entypo/direction.svg#Direction',
	'e/document-landscape': 'entypo/document-landscape.svg#Document_Landscape',
	'e/document': 'entypo/document.svg#Document',
	'e/documents': 'entypo/documents.svg#Documents',
	'e/dot-single': 'entypo/dot-single.svg#Dot_single',
	'e/dots-three-horizontal': 'entypo/dots-three-horizontal.svg#Dots_three_horizontal',
	'e/dots-three-vertical': 'entypo/dots-three-vertical.svg#Dots_three_vertical',
	'e/dots-two-horizontal': 'entypo/dots-two-horizontal.svg#Dots_two_horizontal',
	'e/dots-two-vertical': 'entypo/dots-two-vertical.svg#Dots_two_vertical',
	'e/download': 'entypo/download.svg#Download',
	'e/drink': 'entypo/drink.svg#Drink',
	'e/drive': 'entypo/drive.svg#Drive',
	'e/drop': 'entypo/drop.svg#Drop',
	'e/edit': 'entypo/edit.svg#Edit',
	'e/email': 'entypo/email.svg#Email',
	'e/emoji-flirt': 'entypo/emoji-flirt.svg#Emoji_flirt',
	'e/emoji-happy': 'entypo/emoji-happy.svg#Emoji_happy',
	'e/emoji-neutral': 'entypo/emoji-neutral.svg#Emoji_neutral',
	'e/emoji-sad': 'entypo/emoji-sad.svg#Emoji_sad',
	'e/erase': 'entypo/erase.svg#Erase',
	'e/eraser': 'entypo/eraser.svg#Eraser',
	'e/export': 'entypo/export.svg#Export',
	'e/eye-with-line': 'entypo/eye-with-line.svg#Eye_with_line',
	'e/eye': 'entypo/eye.svg#Eye',
	'e/feather': 'entypo/feather.svg#Feather',
	'e/fingerprint': 'entypo/fingerprint.svg#Fingerprint',
	'e/flag': 'entypo/flag.svg#Flag',
	'e/flash': 'entypo/flash.svg#Flash',
	'e/flashlight': 'entypo/flashlight.svg#Flashlight',
	'e/flat-brush': 'entypo/flat-brush.svg#Flat_brush',
	'e/flow-branch': 'entypo/flow-branch.svg#Flow_branch',
	'e/flow-cascade': 'entypo/flow-cascade.svg#Flow_cascade',
	'e/flow-line': 'entypo/flow-line.svg#Flow_line',
	'e/flow-parallel': 'entypo/flow-parallel.svg#Flow_parallel',
	'e/flow-tree': 'entypo/flow-tree.svg#Flow_tree',
	'e/flower': 'entypo/flower.svg#Flower',
	'e/folder-images': 'entypo/folder-images.svg#Folder_images',
	'e/folder-music': 'entypo/folder-music.svg#Folder_music',
	'e/folder-video': 'entypo/folder-video.svg#Folder_video',
	'e/folder': 'entypo/folder.svg#Folder',
	'e/forward': 'entypo/forward.svg#Forward',
	'e/funnel': 'entypo/funnel.svg#Funnel',
	'e/game-controller': 'entypo/game-controller.svg#Drive',
	'e/gauge': 'entypo/gauge.svg#Gauge',
	'e/globe': 'entypo/globe.svg#Globe',
	'e/graduation-cap': 'entypo/graduation-cap.svg#Graduation_cap',
	'e/grid': 'entypo/grid.svg#Grid',
	'e/hair-cross': 'entypo/hair-cross.svg#Hair_cross',
	'e/hand': 'entypo/hand.svg#Hand',
	'e/heart-outlined': 'entypo/heart-outlined.svg#Heart_outlined',
	'e/heart': 'entypo/heart.svg#Heart',
	'e/help-with-circle': 'entypo/help-with-circle.svg#Help_circled',
	'e/help': 'entypo/help.svg#Help',
	'e/home': 'entypo/home.svg#Home',
	'e/hour-glass': 'entypo/hour-glass.svg#Hour_glass',
	'e/image-inverted': 'entypo/image-inverted.svg#Image_inverted',
	'e/image': 'entypo/image.svg#Image',
	'e/images': 'entypo/images.svg#Images',
	'e/inbox': 'entypo/inbox.svg#Inbox',
	'e/infinity': 'entypo/infinity.svg#Infinity',
	'e/info-with-circle': 'entypo/info-with-circle.svg#Info_circled',
	'e/info': 'entypo/info.svg#Info',
	'e/install': 'entypo/install.svg#Install',
	'e/key': 'entypo/key.svg#Key',
	'e/keyboard': 'entypo/keyboard.svg#Keyboard',
	'e/lab-flask': 'entypo/lab-flask.svg#Lab_flask',
	'e/landline': 'entypo/landline.svg#Landline',
	'e/language': 'entypo/language.svg#Language',
	'e/laptop': 'entypo/laptop.svg#Laptop',
	'e/layers': 'entypo/layers.svg#Layers',
	'e/leaf': 'entypo/leaf.svg#Leaf',
	'e/level-down': 'entypo/level-down.svg#Level_down',
	'e/level-up': 'entypo/level-up.svg#Level_up',
	'e/lifebuoy': 'entypo/lifebuoy.svg#Lifebuoy',
	'e/light-bulb': 'entypo/light-bulb.svg#Light_bulb',
	'e/light-down': 'entypo/light-down.svg#Light_down',
	'e/light-up': 'entypo/light-up.svg#Light_up',
	'e/line-graph': 'entypo/line-graph.svg#Line_graph',
	'e/link': 'entypo/link.svg#Link',
	'e/list': 'entypo/list.svg#List',
	'e/location-pin': 'entypo/location-pin.svg#Location_pin',
	'e/location': 'entypo/location.svg#Location',
	'e/lock-open': 'entypo/lock-open.svg#Lock_open',
	'e/lock': 'entypo/lock.svg#Lock',
	'e/log-out': 'entypo/log-out.svg#Log_out',
	'e/login': 'entypo/login.svg#Login',
	'e/loop': 'entypo/loop.svg#Loop',
	'e/magnet': 'entypo/magnet.svg#Magnet',
	'e/magnifying-glass': 'entypo/magnifying-glass.svg#Magnifying_glass',
	'e/mail': 'entypo/mail.svg#Mail',
	'e/man': 'entypo/man.svg#Man',
	'e/map': 'entypo/map.svg#Map',
	'e/mask': 'entypo/mask.svg#Mask',
	'e/medal': 'entypo/medal.svg#Medal',
	'e/megaphone': 'entypo/megaphone.svg#Megaphone',
	'e/menu': 'entypo/menu.svg#Menu',
	'e/merge': 'entypo/merge.svg#Merge',
	'e/message': 'entypo/message.svg#Message',
	'e/mic': 'entypo/mic.svg#Mic',
	'e/minus': 'entypo/minus.svg#Minus',
	'e/mobile': 'entypo/mobile.svg#Mobile',
	'e/modern-mic': 'entypo/modern-mic.svg#Modern_mic',
	'e/moon': 'entypo/moon.svg#Moon',
	'e/mouse-pointer': 'entypo/mouse-pointer.svg#Mouse_pointer',
	'e/mouse': 'entypo/mouse.svg#Mouse',
	'e/music': 'entypo/music.svg#Music',
	'e/network': 'entypo/network.svg#Network',
	'e/new-message': 'entypo/new-message.svg#New_message',
	'e/new': 'entypo/new.svg#New',
	'e/news': 'entypo/news.svg#News',
	'e/newsletter': 'entypo/newsletter.svg#Newsletter',
	'e/note': 'entypo/note.svg#Note',
	'e/notification': 'entypo/notification.svg#Notification',
	'e/notifications-off': 'entypo/notifications-off.svg#Notifications_off',
	'e/old-mobile': 'entypo/old-mobile.svg#Old_mobile',
	'e/old-phone': 'entypo/old-phone.svg#Old_phone',
	'e/open-book': 'entypo/open-book.svg#Open_book',
	'e/palette': 'entypo/palette.svg#Palette',
	'e/paper-plane': 'entypo/paper-plane.svg#Paper_plane',
	'e/pencil': 'entypo/pencil.svg#Pencil',
	'e/phone': 'entypo/phone.svg#Phone',
	'e/pie-chart': 'entypo/pie-chart.svg#Pie_chart',
	'e/pin': 'entypo/pin.svg#Pin',
	'e/plus': 'entypo/plus.svg#Plus',
	'e/popup': 'entypo/popup.svg#Popup',
	'e/power-plug': 'entypo/power-plug.svg#Power_plug',
	'e/price-ribbon': 'entypo/price-ribbon.svg#Price_ribbon',
	'e/price-tag': 'entypo/price-tag.svg#Price_tag',
	'e/print': 'entypo/print.svg#Print',
	'e/progress-empty': 'entypo/progress-empty.svg#Progress_empty',
	'e/progress-full': 'entypo/progress-full.svg#Progress_full',
	'e/progress-one': 'entypo/progress-one.svg#Progress_one',
	'e/progress-two': 'entypo/progress-two.svg#Progress_two',
	'e/publish': 'entypo/publish.svg#Publish',
	'e/quote': 'entypo/quote.svg#Quote',
	'e/radio': 'entypo/radio.svg#Radio',
	'e/remove-user': 'entypo/remove-user.svg#Remove_user',
	'e/reply-all': 'entypo/reply-all.svg#Reply_all',
	'e/reply': 'entypo/reply.svg#Reply',
	'e/resize-100%': 'entypo/resize-100%.svg#Resize_100_x25_',
	'e/resize-full-screen': 'entypo/resize-full-screen.svg#Resize_full_screen',
	'e/retweet': 'entypo/retweet.svg#Retweet',
	'e/rocket': 'entypo/rocket.svg#Rocket',
	'e/round-brush': 'entypo/round-brush.svg#Round_brush',
	'e/rss': 'entypo/rss.svg#RSS',
	'e/ruler': 'entypo/ruler.svg#Ruler',
	'e/save': 'entypo/save.svg#Save',
	'e/scissors': 'entypo/scissors.svg#Scissors',
	'e/select-arrows': 'entypo/select-arrows.svg#Select_arrows',
	'e/share-alternative': 'entypo/share-alternative.svg#Share',
	'e/share': 'entypo/share.svg#Share',
	'e/shareable': 'entypo/shareable.svg#Share',
	'e/shield': 'entypo/shield.svg#Shield',
	'e/shop': 'entypo/shop.svg#Shop',
	'e/shopping-bag': 'entypo/shopping-bag.svg#Shopping_bag',
	'e/shopping-basket': 'entypo/shopping-basket.svg#Shopping_basket',
	'e/shopping-cart': 'entypo/shopping-cart.svg#Shopping_cart',
	'e/shuffle': 'entypo/shuffle.svg#Shuffle',
	'e/signal': 'entypo/signal.svg#Signal',
	'e/sound-mix': 'entypo/sound-mix.svg#Sound_mix',
	'e/sound-mute': 'entypo/sound-mute.svg#Sound_mute',
	'e/sound': 'entypo/sound.svg#Sound',
	'e/sports-club': 'entypo/sports-club.svg#Sports_club',
	'e/spreadsheet': 'entypo/spreadsheet.svg#Spreadsheet',
	'e/squared-cross': 'entypo/squared-cross.svg#Squared_cross',
	'e/squared-minus': 'entypo/squared-minus.svg#Squared_minus',
	'e/squared-plus': 'entypo/squared-plus.svg#Squared_plus',
	'e/star-outlined': 'entypo/star-outlined.svg#Star_outlined',
	'e/star': 'entypo/star.svg#Star',
	'e/stopwatch': 'entypo/stopwatch.svg#Stopwatch',
	'e/suitcase': 'entypo/suitcase.svg#Brush',
	'e/swap': 'entypo/swap.svg#Swap',
	'e/sweden': 'entypo/sweden.svg#Sweden',
	'e/switch': 'entypo/switch.svg#Switch',
	'e/tablet-mobile-combo': 'entypo/tablet-mobile-combo.svg#Tablet_Mobile_combo',
	'e/tablet': 'entypo/tablet.svg#Tablet',
	'e/tag': 'entypo/tag.svg#Tag',
	'e/text-document-inverted': 'entypo/text-document-inverted.svg#Text_document_inverted',
	'e/text-document': 'entypo/text-document.svg#Text_document',
	'e/text': 'entypo/text.svg#Text',
	'e/thermometer': 'entypo/thermometer.svg#Thermometer',
	'e/thumbs-down': 'entypo/thumbs-down.svg#Thumbs_down',
	'e/thumbs-up': 'entypo/thumbs-up.svg#Thumbs_up',
	'e/thunder-cloud': 'entypo/thunder-cloud.svg#Thunder_cloud',
	'e/ticket': 'entypo/ticket.svg#Ticket',
	'e/time-slot': 'entypo/time-slot.svg#Time_slot',
	'e/tools': 'entypo/tools.svg#Tools',
	'e/traffic-cone': 'entypo/traffic-cone.svg#Traffic_cone',
	'e/trash': 'entypo/trash.svg#Trash',
	'e/tree': 'entypo/tree.svg#Tree',
	'e/triangle-down': 'entypo/triangle-down.svg#Triangle_down',
	'e/triangle-left': 'entypo/triangle-left.svg#Triangle_left',
	'e/triangle-right': 'entypo/triangle-right.svg#Triangle_right',
	'e/triangle-up': 'entypo/triangle-up.svg#Triangle_up',
	'e/trophy': 'entypo/trophy.svg#Trophy',
	'e/tv': 'entypo/tv.svg#TV',
	'e/typing': 'entypo/typing.svg#Typing',
	'e/uninstall': 'entypo/uninstall.svg#Uninstall',
	'e/unread': 'entypo/unread.svg#Unread',
	'e/untag': 'entypo/untag.svg#Untag',
	'e/upload-to-cloud': 'entypo/upload-to-cloud.svg#Upload_to_cloud',
	'e/upload': 'entypo/upload.svg#Upload',
	'e/user': 'entypo/user.svg#User',
	'e/users': 'entypo/users.svg#Users',
	'e/v-card': 'entypo/v-card.svg#V-card',
	'e/video-camera': 'entypo/video-camera.svg#Video_camera',
	'e/video': 'entypo/video.svg#Video',
	'e/vinyl': 'entypo/vinyl.svg#Vinyl',
	'e/voicemail': 'entypo/voicemail.svg#Voicemail',
	'e/wallet': 'entypo/wallet.svg#Wallet',
	'e/warning': 'entypo/warning.svg#Warning',
	'e/water': 'entypo/water.svg#Water'
};